export const mainUrls = [
  'toppages',
  'asp_net_applications',
  'sqlserver_general_statistics',
  '_net_clr_locksandthreads',
  'paging_file',
  'sqlserver_access_methods',
  'asp_net',
  // 'elasticsearch',
  'asp_net_apps_v_',
  'sqlserver_database_mirroring',
  'sqlserver_sql_statistics',
  'processor',
  'web_service',
  'app_pool_was',
  'sqlserver_databases',
  'sqlserver_memory_manager',
  'was_w_wp',
  'memory',
  '_net_clr_exceptions',
  'sqlserver_buffer_manager',
  'w_svc_w_wp',
  'sqlagent_jobs',
  '_net_clr_loading',
  'sqlserver_wait_statistics',
  'sqlserver_buffer_node',
  'physicaldisk',
  'sqlagent_jobsteps',
  // 'es_ruasim_',
  'system',
  '_net_clr_memory',
  'sqlagent_statistics',
  'sqlagent_alerts'
];
